use classicmodels;

-- Creating procedure GETCUSTOMERS()

DELIMITER $$
CREATE PROCEDURE GETCUSTOMERS()
begin
select customerNumber,customerName,contactLastName,contactFirstName 
from customers 
order by contactLastName;
end $$
DELIMITER ;

CALL GETCUSTOMERS();

-- CREATING PROCEDURE GETOFFICEBYCOUNTRY()

DELIMITER //
CREATE PROCEDURE GETOFFICEBYCOUNTRY(IN COUNTRYNAME VARCHAR(255))
BEGIN
SELECT * FROM OFFICES WHERE COUNTRY=COUNTRYNAME;
END //
DELIMITER ;

CALL GETOFFICEBYCOUNTRY('FRANCE');



-- CREATING PROCEDURE GETORDERCOUNTBYSTATUS()

DELIMITER //
CREATE PROCEDURE GETORDERCOUNTBYSTATUS(IN ORDERSTATUS VARCHAR(25),OUT TOTAL INT)
BEGIN
SELECT COUNT(ORDERNUMBER) INTO TOTAL FROM ORDERS WHERE STATUS=ORDERSTATUS;
END //
DELIMITER ;

CALL GETORDERCOUNTBYSTATUS('SHIPPED',@TOTAL);
SELECT @TOTAL;


-- CREATING PROCEDURE SETCOUNTER()

DELIMITER $$
CREATE PROCEDURE SETCOUNTER(INOUT COUNTER INT,IN INC INT)
BEGIN
	SET COUNTER=COUNTER+INC;
END $$
DELIMITER ;

SET @COUNTER=1;
CALL SETCOUNTER(@COUNTER,1);
CALL SETCOUNTER(@COUNTER,1);
CALL SETCOUNTER(@COUNTER,5);
SELECT @COUNTER;

